/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany;

import static com.mycompany.DbConnection.connect;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author odeny
 */
public class ProductDashBoard extends javax.swing.JFrame {
    
     JFrame frame = new JFrame();

    /**
     * Creates new form ProductDashBoard
     */
    public ProductDashBoard() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProductBar = new javax.swing.JPanel();
        createProductLabel = new javax.swing.JLabel();
        updateProductLabel = new javax.swing.JLabel();
        allProductLabel = new javax.swing.JLabel();
        deleteProductLabel = new javax.swing.JLabel();
        BackToDashBoard = new javax.swing.JButton();
        productBarLabel = new javax.swing.JLabel();
        productContent = new javax.swing.JPanel();
        upperPanel = new javax.swing.JPanel();
        searchLabel = new javax.swing.JLabel();
        supportLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        availableLabel = new javax.swing.JLabel();
        damagedPanel = new javax.swing.JPanel();
        damagedLabel = new javax.swing.JLabel();
        outPanel = new javax.swing.JPanel();
        outStockLabel = new javax.swing.JLabel();
        expiredPanel = new javax.swing.JPanel();
        expiredLabel = new javax.swing.JLabel();
        returnPanel = new javax.swing.JPanel();
        returnLabel = new javax.swing.JLabel();
        addPanel = new javax.swing.JPanel();
        addLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Product DashBoard");

        ProductBar.setBackground(new java.awt.Color(0, 51, 153));

        createProductLabel.setFont(new java.awt.Font("PT Serif", 0, 13)); // NOI18N
        createProductLabel.setForeground(new java.awt.Color(255, 255, 255));
        createProductLabel.setText("Create Product");
        createProductLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createProductLabelMouseClicked(evt);
            }
        });

        updateProductLabel.setFont(new java.awt.Font("PT Serif", 0, 13)); // NOI18N
        updateProductLabel.setForeground(new java.awt.Color(255, 255, 255));
        updateProductLabel.setText("Update Product");
        updateProductLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateProductMouseClicked(evt);
            }
        });

        allProductLabel.setFont(new java.awt.Font("PT Serif", 0, 13)); // NOI18N
        allProductLabel.setForeground(new java.awt.Color(255, 255, 255));
        allProductLabel.setText("Products");
        allProductLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allProductsMouseClicked(evt);
            }
        });

        deleteProductLabel.setFont(new java.awt.Font("PT Serif", 0, 13)); // NOI18N
        deleteProductLabel.setForeground(new java.awt.Color(255, 255, 255));
        deleteProductLabel.setText("Delete Product");
        deleteProductLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteProductLabelMouseClicked(evt);
            }
        });

        BackToDashBoard.setBackground(new java.awt.Color(0, 51, 153));
        BackToDashBoard.setFont(new java.awt.Font("PT Serif", 0, 14)); // NOI18N
        BackToDashBoard.setForeground(new java.awt.Color(255, 255, 255));
        BackToDashBoard.setText("Dashbaoard");
        BackToDashBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToDashBoardActionPerformed(evt);
            }
        });

        productBarLabel.setBackground(new java.awt.Color(0, 51, 153));
        productBarLabel.setFont(new java.awt.Font("PT Serif", 0, 14)); // NOI18N
        productBarLabel.setForeground(new java.awt.Color(255, 255, 255));
        productBarLabel.setText("Product DashBoard");

        javax.swing.GroupLayout ProductBarLayout = new javax.swing.GroupLayout(ProductBar);
        ProductBar.setLayout(ProductBarLayout);
        ProductBarLayout.setHorizontalGroup(
            ProductBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProductBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteProductLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createProductLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateProductLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(allProductLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ProductBarLayout.createSequentialGroup()
                        .addComponent(BackToDashBoard)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(productBarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ProductBarLayout.setVerticalGroup(
            ProductBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productBarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(createProductLabel)
                .addGap(18, 18, 18)
                .addComponent(updateProductLabel)
                .addGap(18, 18, 18)
                .addComponent(allProductLabel)
                .addGap(26, 26, 26)
                .addComponent(deleteProductLabel)
                .addGap(30, 30, 30)
                .addComponent(BackToDashBoard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        productContent.setBackground(new java.awt.Color(255, 255, 255));

        upperPanel.setBackground(new java.awt.Color(255, 255, 255));

        searchLabel.setBackground(new java.awt.Color(255, 255, 255));
        searchLabel.setFont(new java.awt.Font("PT Serif", 0, 13)); // NOI18N
        searchLabel.setForeground(new java.awt.Color(51, 0, 51));
        searchLabel.setText("Search");

        supportLabel.setBackground(new java.awt.Color(255, 255, 255));
        supportLabel.setFont(new java.awt.Font("PT Serif", 0, 13)); // NOI18N
        supportLabel.setForeground(new java.awt.Color(51, 0, 51));
        supportLabel.setText("Help");
        supportLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout upperPanelLayout = new javax.swing.GroupLayout(upperPanel);
        upperPanel.setLayout(upperPanelLayout);
        upperPanelLayout.setHorizontalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(searchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(supportLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        upperPanelLayout.setVerticalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supportLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        availableLabel.setBackground(new java.awt.Color(255, 255, 255));
        availableLabel.setFont(new java.awt.Font("PT Serif", 0, 13)); // NOI18N
        availableLabel.setForeground(new java.awt.Color(51, 0, 51));
        availableLabel.setText("Available");
        availableLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                availableMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(availableLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(availableLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        damagedPanel.setBackground(new java.awt.Color(255, 255, 255));

        damagedLabel.setBackground(new java.awt.Color(255, 255, 255));
        damagedLabel.setFont(new java.awt.Font("PT Serif", 0, 13)); // NOI18N
        damagedLabel.setForeground(new java.awt.Color(51, 0, 51));
        damagedLabel.setText("Damaged");
        damagedLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                damageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout damagedPanelLayout = new javax.swing.GroupLayout(damagedPanel);
        damagedPanel.setLayout(damagedPanelLayout);
        damagedPanelLayout.setHorizontalGroup(
            damagedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(damagedPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(damagedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        damagedPanelLayout.setVerticalGroup(
            damagedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(damagedPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(damagedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        outPanel.setBackground(new java.awt.Color(255, 255, 255));

        outStockLabel.setBackground(new java.awt.Color(255, 255, 255));
        outStockLabel.setFont(new java.awt.Font("PT Serif", 0, 13)); // NOI18N
        outStockLabel.setForeground(new java.awt.Color(51, 0, 51));
        outStockLabel.setText("Out Of Stock");

        javax.swing.GroupLayout outPanelLayout = new javax.swing.GroupLayout(outPanel);
        outPanel.setLayout(outPanelLayout);
        outPanelLayout.setHorizontalGroup(
            outPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(outStockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        outPanelLayout.setVerticalGroup(
            outPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, outPanelLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(outStockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        expiredPanel.setBackground(new java.awt.Color(255, 255, 255));

        expiredLabel.setBackground(new java.awt.Color(255, 255, 255));
        expiredLabel.setFont(new java.awt.Font("PT Serif", 0, 13)); // NOI18N
        expiredLabel.setForeground(new java.awt.Color(51, 0, 51));
        expiredLabel.setText("Expired");
        expiredLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                expiredMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout expiredPanelLayout = new javax.swing.GroupLayout(expiredPanel);
        expiredPanel.setLayout(expiredPanelLayout);
        expiredPanelLayout.setHorizontalGroup(
            expiredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(expiredPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(expiredLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        expiredPanelLayout.setVerticalGroup(
            expiredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, expiredPanelLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(expiredLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        returnPanel.setBackground(new java.awt.Color(255, 255, 255));

        returnLabel.setBackground(new java.awt.Color(255, 255, 255));
        returnLabel.setFont(new java.awt.Font("PT Serif", 0, 13)); // NOI18N
        returnLabel.setForeground(new java.awt.Color(51, 0, 51));
        returnLabel.setText("Returns");
        returnLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout returnPanelLayout = new javax.swing.GroupLayout(returnPanel);
        returnPanel.setLayout(returnPanelLayout);
        returnPanelLayout.setHorizontalGroup(
            returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(returnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        returnPanelLayout.setVerticalGroup(
            returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, returnPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(returnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        addPanel.setBackground(new java.awt.Color(255, 255, 255));

        addLabel.setBackground(new java.awt.Color(255, 255, 255));
        addLabel.setFont(new java.awt.Font("PT Serif", 0, 13)); // NOI18N
        addLabel.setForeground(new java.awt.Color(51, 0, 51));
        addLabel.setText("Add New");
        addLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addNewMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(addLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(addLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout productContentLayout = new javax.swing.GroupLayout(productContent);
        productContent.setLayout(productContentLayout);
        productContentLayout.setHorizontalGroup(
            productContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(productContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productContentLayout.createSequentialGroup()
                        .addComponent(upperPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(productContentLayout.createSequentialGroup()
                        .addGroup(productContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(returnPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(outPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                        .addGroup(productContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(damagedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(expiredPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(63, 63, 63))))
        );
        productContentLayout.setVerticalGroup(
            productContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productContentLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(upperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(productContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(damagedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(productContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expiredPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(productContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(returnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProductBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(productContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProductBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    CreateUpdateProduct createUpdateProduct = new CreateUpdateProduct();
    private void BackToDashBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToDashBoardActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new DashBoard().setVisible(true);
    }//GEN-LAST:event_BackToDashBoardActionPerformed

    private void deleteProductLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteProductLabelMouseClicked
        // TODO add your handling code here:
       JOptionPane.showConfirmDialog(productContent, "Are you sure you want to delete this product");
    }//GEN-LAST:event_deleteProductLabelMouseClicked

    private void allProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allProductsMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        
        DefaultTableModel model = new DefaultTableModel();
        JTable table = new JTable(model);
        
         try {
             Connection connection = connect();
        String query = "SELECT * FROM products";
        PreparedStatement preparedStatement = connection.prepareStatement(query);
        ResultSet resultSet = preparedStatement.executeQuery();
        // Add columns to the table
        model.addColumn("Product Name");
        model.addColumn("Industry");
        model.addColumn("Description");
        model.addColumn("Price");
        model.addColumn("Unit of Measure");
        model.addColumn("Photo");

        // Iterate through the ResultSet and add rows to the table
        while (resultSet.next()) {
            String productName = resultSet.getString("product_name");
            String industry = resultSet.getString("industry");
            String description = resultSet.getString("description");
            double price = resultSet.getDouble("price");
            String unitOfMeasure = resultSet.getString("unit_of_measure");
            String photo = resultSet.getString("photo");

            model.addRow(new Object[]{productName, industry, description, price, unitOfMeasure, photo});
        }

    } catch (SQLException ex) {
        ex.printStackTrace();
    }
          JScrollPane scrollPane = new JScrollPane(table);
    frame.setContentPane(scrollPane);
    frame.pack();
    frame.setLocationRelativeTo(null);
    frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    frame.addWindowListener(new WindowAdapter() {
        @Override
        public void windowClosed(WindowEvent e) {
            new ProductDashBoard().setVisible(true);
        }
    });
    frame.setVisible(true);
    }//GEN-LAST:event_allProductsMouseClicked

    private void updateProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateProductMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        createUpdateProduct.setVisible(true);
    }//GEN-LAST:event_updateProductMouseClicked

    private void createProductLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createProductLabelMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        createUpdateProduct.setVisible(true);
    }//GEN-LAST:event_createProductLabelMouseClicked

    private void helpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Call sopport  072000000");
    }//GEN-LAST:event_helpMouseClicked

    private void addNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNewMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        createUpdateProduct.setVisible(true);
    }//GEN-LAST:event_addNewMouseClicked

    private void availableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_availableMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        
        DefaultTableModel model = new DefaultTableModel();
        JTable table = new JTable(model);
        
         try {
             Connection connection = connect();
        String query = "SELECT * FROM products";
        PreparedStatement preparedStatement = connection.prepareStatement(query);
        ResultSet resultSet = preparedStatement.executeQuery();
        // Add columns to the table
        model.addColumn("Product Name");
        model.addColumn("Industry");
        model.addColumn("Description");
        model.addColumn("Price");
        model.addColumn("Unit of Measure");
        model.addColumn("Photo");

        // Iterate through the ResultSet and add rows to the table
        while (resultSet.next()) {
            String productName = resultSet.getString("product_name");
            String industry = resultSet.getString("industry");
            String description = resultSet.getString("description");
            double price = resultSet.getDouble("price");
            String unitOfMeasure = resultSet.getString("unit_of_measure");
            String photo = resultSet.getString("photo");

            model.addRow(new Object[]{productName, industry, description, price, unitOfMeasure, photo});
        }

    } catch (SQLException ex) {
        ex.printStackTrace();
    }
          JScrollPane scrollPane = new JScrollPane(table);
    frame.setContentPane(scrollPane);
    frame.pack();
    frame.setLocationRelativeTo(null);
    frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    frame.addWindowListener(new WindowAdapter() {
        @Override
        public void windowClosed(WindowEvent e) {
            new ProductDashBoard().setVisible(true);
        }
    });
    frame.setVisible(true);
    }//GEN-LAST:event_availableMouseClicked

    private void damageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_damageMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(productContent, "You do not have Damaged Stock");
    }//GEN-LAST:event_damageMouseClicked

    private void expiredMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expiredMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(productContent, "You do not have Expired Stock");
    }//GEN-LAST:event_expiredMouseClicked

    private void returnsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnsMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(productContent, "You do not have Any Returns");
    }//GEN-LAST:event_returnsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductDashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToDashBoard;
    private javax.swing.JPanel ProductBar;
    private javax.swing.JLabel addLabel;
    private javax.swing.JPanel addPanel;
    private javax.swing.JLabel allProductLabel;
    private javax.swing.JLabel availableLabel;
    javax.swing.JLabel createProductLabel;
    private javax.swing.JLabel damagedLabel;
    private javax.swing.JPanel damagedPanel;
    private javax.swing.JLabel deleteProductLabel;
    private javax.swing.JLabel expiredLabel;
    private javax.swing.JPanel expiredPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel outPanel;
    private javax.swing.JLabel outStockLabel;
    private javax.swing.JLabel productBarLabel;
    private javax.swing.JPanel productContent;
    private javax.swing.JLabel returnLabel;
    private javax.swing.JPanel returnPanel;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JLabel supportLabel;
    private javax.swing.JLabel updateProductLabel;
    private javax.swing.JPanel upperPanel;
    // End of variables declaration//GEN-END:variables
}
